### ISSUE TITLE
allowSplit = TRUE does not work

### ISSUE THREAD

**Issue by lindeloev** [mikemeredith/HDInterval#5]
`allowSplit` does not work on `HDInterval` 2.2:

Here's a trimodal vector:
```r
x = c(rnorm(500, 30, 3), rnorm(200, 50, 1.5), 60 + rexp(200, 0.1))
hist(x, breaks = 100)
```
![image](https://user-images.githubusercontent.com/1439417/99793418-f55b0000-2b28-11eb-9215-3c64a50a386a.png)

But it returns only a single continuous interval:
```r
HDInterval::hdi(density(x), 0.95, allowSplit = TRUE)
```
```
        begin      end
[1,] 19.62601 77.12184
attr(,"credMass")
[1] 0.95
attr(,"height")
[1] 0.004363256
```

Thanks for a great package otherwise!

**Comment by mikemeredith** [comment]
Hi Jonas, Thanks for raising the issue and providing a nice example.

The problem here is that the density fit with default bandwidth doesn't fit very well and the troughs between the modes are not deep enough.
```
set.seed(2020)
x = c(rnorm(500, 30, 3), rnorm(200, 50, 1.5), 60 + rexp(200, 0.1))
hist(x, breaks = 100, freq=FALSE)
dens1 <- density(x)
lines(dens1, col='red', lwd=2)
hdi <- hdi(dens1, allowSplit=TRUE)
(ht <- attr(hdi, "height"))
segments(hdi[, 1], ht, hdi[, 2], ht, lwd=3, col='blue')
```
<img width="306" alt="hist+dens1" src="https://user-images.githubusercontent.com/1969451/99861130-2e01e480-2bd0-11eb-9579-803aa9332f9b.png">
The curve between the modes doesn't (quite) drop below the threshold. The density doesn't capture the shape of the distribution of the data, but we can change the bandwidth. The `density` help page says:

> The default, "nrd0", has remained the default for historical and compatibility reasons, rather than as a general recommendation, where e.g., "SJ" would rather fit, ...

```
dens2 <- density(x, bw="SJ")
hist(x, breaks = 100, freq=FALSE)
lines(dens2, col='red', lwd=2)
hdi <- hdi(dens2, allowSplit=TRUE)
ht <- attr(hdi, "height")
segments(hdi[, 1], ht, hdi[, 2], ht, lwd=3, col='blue')
```
<img width="306" alt="hist+dens2" src="https://user-images.githubusercontent.com/1969451/99861526-49b9ba80-2bd1-11eb-85a8-4fe0e1e60b7b.png">

That looks a lot better and we can now distinguish 4 modes with the seed I used.

The issue is with the crappy old default for the `density` function rather than with `hdi`, but worth a note on the help page next time I update.

**Comment by lindeloev** [comment]
Thank you, that solves it for me! Didn't know about the poor default for `bw` - this will be useful in many other situations too. Feel free to close this issue.
